# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nested.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from profanedb.protobuf import options_pb2 as profanedb_dot_protobuf_dot_options__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='nested.proto',
  package='schema',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cnested.proto\x12\x06schema\x1a profanedb/protobuf/options.proto\"1\n\x0e\x45xternalNested\x12\x1f\n\x10\x66ield_one_double\x18\x01 \x01(\x01\x42\x05\xe2@\x02\x08\x01\x62\x06proto3'
  ,
  dependencies=[profanedb_dot_protobuf_dot_options__pb2.DESCRIPTOR,])




_EXTERNALNESTED = _descriptor.Descriptor(
  name='ExternalNested',
  full_name='schema.ExternalNested',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='field_one_double', full_name='schema.ExternalNested.field_one_double', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\342@\002\010\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=107,
)

DESCRIPTOR.message_types_by_name['ExternalNested'] = _EXTERNALNESTED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExternalNested = _reflection.GeneratedProtocolMessageType('ExternalNested', (_message.Message,), {
  'DESCRIPTOR' : _EXTERNALNESTED,
  '__module__' : 'nested_pb2'
  # @@protoc_insertion_point(class_scope:schema.ExternalNested)
  })
_sym_db.RegisterMessage(ExternalNested)


_EXTERNALNESTED.fields_by_name['field_one_double']._options = None
# @@protoc_insertion_point(module_scope)
